### ISSUE TITLE
Can not find DOMXSS.js file

### ISSUE THREAD

**Issue by rusboy** [WebGoat/WebGoat-Lessons#53]
2016-02-10 13:18:45,175 DEBUG - HH Leaving Session_id: D4DE2ACA5E2F9D9203D1475B4A60D504
java.io.FileNotFoundException: d:\Pentest\WebGoat\.extract\webapps\WebGoat\WebGoat\plugin_extracted\plugin\DOMXSS\js\js\DOMXSS.js (The syste
m cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at org.owasp.webgoat.plugin.DOMXSS.getFileContent(DOMXSS.java:287)
        at org.owasp.webgoat.plugin.DOMXSS.doStage5(DOMXSS.java:139)
        at org.owasp.webgoat.lessons.SequentialLessonAdapter.createStagedContent(SequentialLessonAdapter.java:114)
        at org.owasp.webgoat.plugin.DOMXSS.createContent(DOMXSS.java:38)
        at org.owasp.webgoat.lessons.AbstractLesson.handleRequest(AbstractLesson.java:868)
        at org.owasp.webgoat.HammerHead.makeScreen(HammerHead.java:300)
        at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:148)
        at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:104)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFil
ter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingF
ilter.java:199)

**Comment by nbaars** [comment]
Closing because this has already been merged
